CREATE TABLE User(
   id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
   user_id VARCHAR(32) NOT NULL,
   name VARCHAR(20) NOT NULL,
   mobile VARCHAR(11) NOT NULL,
   created_at DATE NOT NULL,
   updated_at DATE NOT NULL,
) DEFAULT CHARSET = utf8;
